name: Run tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  build-linux-cpp:
    name: Run tests on ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install libhdf5-openmpi-dev libopenmpi-dev

      - name: Build and run unittests
        env:
          CC: mpicc
          CXX: mpic++
        run: |
          ./ci/cpp_test.sh

  build-linux-python:
    name: Run python tests on ubuntu-20.04
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install libhdf5-openmpi-dev libopenmpi-dev

      - name: Build and run unittests
        env:
          CC: mpicc
          CXX: mpic++
        run: |
            ./ci/python_test.sh
